version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis_default.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis_default.conf --appendonly yes
  wvp:
    build:
      context: ./wvp
      args:
        gitUrl: "https://gitee.com/pan648540858"
        zlmGitUrl: "https://gitee.com/xia-chu/ZLMediaKit"
    restart: always
    ports:
      - "5061:5060"
      - "5061:5060/udp"
      - "18081:18080"
      - "80:80"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "30000-30500:30000-30500/tcp"
      - "30000-30500:30000-30500/udp"
    volumes:
      - ./video:/opt/media/www/record/
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./logs/media:/opt/media/log/
    environment:
      TZ: "Asia/Shanghai"
      # [必须修改] 本机的IP
      WVP_HOST: 127.0.0.1
      WVP_PWD: aseqw_+hiy123
      WVP_DOMAIN: 6101130049
      WVP_ID: 61011300490000000001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 6
      REDIS_PWD: root
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      WVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      WVP_CONFIG:
    depends_on:
      - redis
  mysql:
    image: mysql  # 原镜像`mysql:5.7`
    container_name: mysql                                    # 容器名为'mysql'
    restart: unless-stopped
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - /home/zyadmin/project/mysql/data:/var/lib/mysql
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root        # 设置root用户密码
    #  MYSQL_DATABASE: root              # 初始化的数据库名称